# Redirect routes that redirect base paths like /mappings to /mappings/list
# Specified in order to keep the context (e.g. siteaccess in eZ Platform)
# which is otherwise lost with automatic redirect in RedirectableUrlMatcher
# See: https://github.com/symfony/symfony/issues/12141

ngbm_admin:
    path: /admin
    methods: [GET]
    defaults:
        _controller: "Symfony\\Bundle\\FrameworkBundle\\Controller\\RedirectController::redirectAction"
        route: ngbm_admin_layout_resolver_index
        permanent: true

ngbm_admin_slash:
    path: /admin/
    methods: [GET]
    defaults:
        _controller: "Symfony\\Bundle\\FrameworkBundle\\Controller\\RedirectController::redirectAction"
        route: ngbm_admin_layout_resolver_index
        permanent: true

ngbm_admin_layout_resolver_root:
    path: /admin/mappings
    methods: [GET]
    defaults:
        _controller: "Symfony\\Bundle\\FrameworkBundle\\Controller\\RedirectController::redirectAction"
        route: ngbm_admin_layout_resolver_index
        permanent: true

ngbm_admin_layout_resolver_root_slash:
    path: /admin/mappings/
    methods: [GET]
    defaults:
        _controller: "Symfony\\Bundle\\FrameworkBundle\\Controller\\RedirectController::redirectAction"
        route: ngbm_admin_layout_resolver_index
        permanent: true

ngbm_admin_layouts_root:
    path: /admin/layouts
    methods: [GET]
    defaults:
        _controller: "Symfony\\Bundle\\FrameworkBundle\\Controller\\RedirectController::redirectAction"
        route: ngbm_admin_layouts_index
        permanent: true

ngbm_admin_layouts_root_slash:
    path: /admin/layouts/
    methods: [GET]
    defaults:
        _controller: "Symfony\\Bundle\\FrameworkBundle\\Controller\\RedirectController::redirectAction"
        route: ngbm_admin_layouts_index
        permanent: true

ngbm_admin_shared_layouts_root:
    path: /admin/shared_layouts
    methods: [GET]
    defaults:
        _controller: "Symfony\\Bundle\\FrameworkBundle\\Controller\\RedirectController::redirectAction"
        route: ngbm_admin_shared_layouts_index
        permanent: true

ngbm_admin_shared_layouts_root_slash:
    path: /admin/shared_layouts/
    methods: [GET]
    defaults:
        _controller: "Symfony\\Bundle\\FrameworkBundle\\Controller\\RedirectController::redirectAction"
        route: ngbm_admin_shared_layouts_index
        permanent: true
