_nglayouts_app_api_config:
    resource: "api/config.yml"

_nglayouts_app_api_blocks:
    resource: "api/blocks.yml"
    prefix: /{locale}

_nglayouts_app_api_block_collections:
    resource: "api/block_collections.yml"
    prefix: /{locale}

_nglayouts_app_api_collections:
    resource: "api/collections.yml"

_nglayouts_app_api_layouts:
    resource: "api/layouts.yml"
