_nglayouts_app_api_config:
    resource: "api/config.yaml"

_nglayouts_app_api_blocks:
    resource: "api/blocks.yaml"
    prefix: /{locale}

_nglayouts_app_api_block_collections:
    resource: "api/block_collections.yaml"
    prefix: /{locale}

_nglayouts_app_api_collections:
    resource: "api/collections.yaml"

_nglayouts_app_api_layouts:
    resource: "api/layouts.yaml"
