nglayouts_app:
    path: /app
    methods: [GET]
    defaults:
        _controller: 'netgen_layouts.controller.app.index'

nglayouts_app_slash:
    path: /app/
    methods: [GET]
    defaults:
        _controller: 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction'
        route: nglayouts_app
        permanent: true

nglayouts_app_layout_form_create:
    path: /app/layouts/form/create
    methods: [GET, POST]
    defaults:
        _controller: 'netgen_layouts.controller.app.layout.create_form'

nglayouts_app_layout_form_edit:
    path: /app/layouts/{layoutId}/form/edit
    methods: [GET, POST]
    defaults:
        _controller: 'netgen_layouts.controller.app.layout.edit_form'

nglayouts_app_block_edit:
    path: /app/{locale}/blocks/{blockId}/edit
    methods: [GET]
    defaults:
        _controller: 'netgen_layouts.controller.app.block.edit'
        _ngbm_status: draft

nglayouts_app_block_form_edit:
    path: /app/{locale}/blocks/{blockId}/form/edit/{formName}
    methods: [GET, POST]
    defaults:
        _controller: 'netgen_layouts.controller.app.block.edit_form'
        _ngbm_status: draft

nglayouts_app_block_form_edit_config:
    path: /app/{locale}/blocks/{blockId}/config/edit/{configKey}
    methods: [GET, POST]
    defaults:
        _controller: 'netgen_layouts.controller.app.block.edit_config_form'
        _ngbm_status: draft
        configKey: null

nglayouts_app_collection_collection_form_edit:
    path: /app/collections/{collectionId}/form/edit/full
    methods: [GET, POST]
    defaults:
        _controller: 'netgen_layouts.controller.app.collection.edit_collection_form'
        _ngbm_status: draft

nglayouts_app_collection_form_edit_item_config:
    path: /app/collections/item/{itemId}/config/edit/{configKey}
    methods: [GET, POST]
    defaults:
        _controller: 'netgen_layouts.controller.app.collection.edit_item_config_form'
        _ngbm_status: draft
        configKey: null

nglayouts_app_collection_query_form_edit:
    path: /app/{locale}/collections/query/{queryId}/form/edit
    methods: [GET, POST]
    defaults:
        _controller: 'netgen_layouts.controller.app.collection.edit_query_form'
        _ngbm_status: draft
