nglayouts_dev_app:
    path: /dev/app
    controller: netgen_layouts.controller.app.index
    methods: [GET]

nglayouts_dev_app_slash:
    path: /dev/app/
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction'
    methods: [GET]
    defaults:
        route: nglayouts_dev_app
        permanent: true
