view:
    item_view:
        default:
            invalid:
                template: "@NetgenLayouts/item/invalid_item.html.twig"
                match:
                    item\value_type: "null"
        api:
            slot:
                template: "@NetgenLayouts/api/item/slot.html.twig"
                match:
                    item\value_type: slot
            invalid:
                template: "@NetgenLayouts/api/item/invalid_item.html.twig"
                match:
                    item\value_type: "null"
