view:
    item_view:
        default:
            invalid:
                template: "@NetgenLayouts/item/invalid_item.html.twig"
                match:
                    item\value_type: "null"
        api:
            unknown:
                template: "@NetgenLayouts/api/item/unknown_item.html.twig"
                match:
                    item\value_type: unknown
            invalid:
                template: "@NetgenLayouts/api/item/invalid_item.html.twig"
                match:
                    item\value_type: "null"
