view:
    layout_view:
        default:
            invalid:
                template: "@NetgenLayouts/layout/invalid_layout.html.twig"
                match:
                    layout\type: "null"
        app:
            invalid:
                template: "@NetgenLayouts/app/layout/invalid_layout.html.twig"
                match:
                    layout\type: "null"
