services:
    netgen_layouts.layout.resolver.registry.target_type:
        class: Netgen\Layouts\Layout\Resolver\Registry\TargetTypeRegistry
        public: true
        arguments:
            - !tagged netgen_block_manager.layout.resolver.target_type

    netgen_layouts.layout.resolver.registry.condition_type:
        class: Netgen\Layouts\Layout\Resolver\Registry\ConditionTypeRegistry
        public: true
        arguments:
            - !tagged netgen_block_manager.layout.resolver.condition_type

    netgen_layouts.layout.resolver:
        class: Netgen\Layouts\Layout\Resolver\LayoutResolver
        arguments:
            - "@netgen_layouts.api.service.layout_resolver"
            - "@netgen_layouts.layout.resolver.registry.target_type"
            - "@request_stack"
