services:
    netgen_block_manager.view.view_renderer:
        class: Netgen\BlockManager\View\ViewRenderer
        arguments:
            - "@event_dispatcher"
            - "@twig"

    netgen_block_manager.view.view_builder:
        class: Netgen\BlockManager\View\ViewBuilder
        public: true
        arguments:
            - "@netgen_block_manager.view.template_resolver"
            - "@event_dispatcher"
            - !tagged netgen_block_manager.view.provider

    netgen_block_manager.view.renderer:
        class: Netgen\BlockManager\View\Renderer
        lazy: true
        arguments:
            - "@netgen_block_manager.view.view_builder"
            - "@netgen_block_manager.view.view_renderer"

    netgen_block_manager.view.template_resolver:
        class: Netgen\BlockManager\View\TemplateResolver
        lazy: true
        arguments:
            - []
            - "@=service('netgen_block_manager.configuration').getParameter('view')"
