nglayouts_app_api_config_config:
    path: /config
    controller: netgen_layouts.controller.api.config.load_config
    methods: [GET]

nglayouts_app_api_config_block_types:
    path: /config/block_types
    controller: netgen_layouts.controller.api.config.load_block_types
    methods: [GET]

nglayouts_app_api_config_layout_types:
    path: /config/layout_types
    controller: netgen_layouts.controller.api.config.load_layout_types
    methods: [GET]
