nglayouts_app_api_layouts_shared:
    path: /layouts/shared
    controller: netgen_layouts.controller.api.layout.load_shared_layouts
    methods: [GET]

nglayouts_app_api_layouts_load:
    path: /layouts/{layoutId}
    controller: netgen_layouts.controller.api.layout.load
    methods: [GET]

nglayouts_app_api_layouts_blocks:
    path: /{locale}/layouts/{layoutId}/blocks
    controller: netgen_layouts.controller.api.layout.load_layout_blocks
    methods: [GET]

nglayouts_app_api_layouts_zone_blocks:
    path: /{locale}/layouts/{layoutId}/zones/{zoneIdentifier}/blocks
    controller: netgen_layouts.controller.api.layout.load_zone_blocks
    methods: [GET]

nglayouts_app_api_layouts_zone_link:
    path: /layouts/{layoutId}/zones/{zoneIdentifier}/link
    controller: netgen_layouts.controller.api.layout.link_zone
    methods: [POST]
    defaults:
        _nglayouts_status: draft

nglayouts_app_api_layouts_zone_unlink:
    path: /layouts/{layoutId}/zones/{zoneIdentifier}/link
    controller: netgen_layouts.controller.api.layout.unlink_zone
    methods: [DELETE]
    defaults:
        _nglayouts_status: draft

nglayouts_app_api_layouts_create:
    path: /layouts
    controller: netgen_layouts.controller.api.layout.create
    methods: [POST]

nglayouts_app_api_layouts_copy:
    path: /layouts/{layoutId}/copy
    controller: netgen_layouts.controller.api.layout.copy
    methods: [POST]

nglayouts_app_api_layouts_change_type:
    path: /layouts/{layoutId}/change_type
    controller: netgen_layouts.controller.api.layout.change_type
    methods: [POST]
    defaults:
        _nglayouts_status: draft

nglayouts_app_api_layouts_create_draft:
    path: /layouts/{layoutId}/draft
    controller: netgen_layouts.controller.api.layout.create_draft
    methods: [POST]
    defaults:
        _nglayouts_status: published

nglayouts_app_api_layouts_discard_draft:
    path: /layouts/{layoutId}/draft
    controller: netgen_layouts.controller.api.layout.discard_draft
    methods: [DELETE]
    defaults:
        _nglayouts_status: draft

nglayouts_app_api_layouts_publish:
    path: /layouts/{layoutId}/publish
    controller: netgen_layouts.controller.api.layout.publish_draft
    methods: [POST]
    defaults:
        _nglayouts_status: draft

nglayouts_app_api_layouts_restore:
    path: /layouts/{layoutId}/restore
    controller: netgen_layouts.controller.api.layout.restore_from_archive
    methods: [POST]
    defaults:
        _nglayouts_status: archived

nglayouts_app_api_layouts_delete:
    path: /layouts/{layoutId}
    controller: netgen_layouts.controller.api.layout.delete
    methods: [DELETE]
    defaults:
        _nglayouts_status: published
