nglayouts_api_v1_blocks_load:
    path: /blocks/{blockId}
    methods: [GET]
    defaults:
        _controller: 'netgen_layouts.controller.api.v1.block.load'

nglayouts_api_v1_blocks_create:
    path: /blocks/{blockId}
    methods: [POST]
    defaults:
        _controller: 'netgen_layouts.controller.api.v1.block.create'

nglayouts_api_v1_blocks_create_in_zone:
    path: /blocks
    methods: [POST]
    defaults:
        _controller: 'netgen_layouts.controller.api.v1.block.create_in_zone'

nglayouts_api_v1_blocks_copy:
    path: /blocks/{blockId}/copy
    methods: [POST]
    defaults:
        _controller: 'netgen_layouts.controller.api.v1.block.copy'
        _nglayouts_status: draft

nglayouts_api_v1_blocks_copy_to_zone:
    path: /blocks/{blockId}/copy/zone
    methods: [POST]
    defaults:
        _controller: 'netgen_layouts.controller.api.v1.block.copy_to_zone'
        _nglayouts_status: draft

nglayouts_api_v1_blocks_move:
    path: /blocks/{blockId}/move
    methods: [POST]
    defaults:
        _controller: 'netgen_layouts.controller.api.v1.block.move'
        _nglayouts_status: draft

nglayouts_api_v1_blocks_move_to_zone:
    path: /blocks/{blockId}/move/zone
    methods: [POST]
    defaults:
        _controller: 'netgen_layouts.controller.api.v1.block.move_to_zone'
        _nglayouts_status: draft

nglayouts_api_v1_blocks_restore:
    path: /blocks/{blockId}/restore
    methods: [POST]
    defaults:
        _controller: 'netgen_layouts.controller.api.v1.block.restore'
        _nglayouts_status: draft

nglayouts_api_v1_blocks_delete:
    path: /blocks/{blockId}
    methods: [DELETE]
    defaults:
        _controller: 'netgen_layouts.controller.api.v1.block.delete'
        _nglayouts_status: draft
