nglayouts_admin_layouts_index:
    path: /list
    methods: [GET]
    defaults:
        _controller: 'netgen_layouts.controller.admin.layouts.index'

nglayouts_admin_layouts_layout_copy:
    path: /{layoutId}/copy
    methods: [GET, POST]
    defaults:
        _controller: 'netgen_layouts.controller.admin.layouts.copy_layout_form'

nglayouts_admin_layouts_export:
    path: /export
    methods: [POST]
    defaults:
        _controller: 'netgen_layouts.controller.admin.layouts.export_layouts'

nglayouts_admin_layouts_layout_delete:
    path: /{layoutId}/delete
    methods: [GET, DELETE]
    defaults:
        _controller: 'netgen_layouts.controller.admin.layouts.delete_layout'

nglayouts_admin_layouts_cache:
    path: /{layoutId}/cache
    methods: [GET, POST]
    defaults:
        _controller: 'netgen_layouts.controller.admin.layouts.clear_layout_cache'
        _ngbm_status: published
