nglayouts_admin_shared_layouts_index:
    path: /list
    controller: netgen_layouts.controller.admin.shared_layouts.index
    methods: [GET]

nglayouts_admin_shared_layouts_related_layouts:
    path: /{layoutId}/related_layouts
    controller: netgen_layouts.controller.admin.shared_layouts.related_layouts
    methods: [GET]
    defaults:
        _nglayouts_status: published

nglayouts_admin_shared_layouts_layout_copy:
    path: /{layoutId}/copy
    controller: netgen_layouts.controller.admin.layouts.copy_layout_form
    methods: [GET, POST]

nglayouts_admin_shared_layouts_export:
    path: /export
    controller: netgen_layouts.controller.admin.layouts.export_layouts
    methods: [POST]

nglayouts_admin_shared_layouts_layout_delete:
    path: /{layoutId}/delete
    controller: netgen_layouts.controller.admin.layouts.delete_layout
    methods: [GET, DELETE]

nglayouts_admin_shared_layouts_cache_related_layouts:
    path: /{layoutId}/cache/related_layouts
    controller: netgen_layouts.controller.admin.shared_layouts.clear_related_layouts_cache
    methods: [GET, POST]
    defaults:
        _nglayouts_status: published
