parameters:
    netgen_block_manager.debug.block_collector.enabled_contexts: ['default']

services:
    netgen_block_manager.debug.data_collector:
        class: Netgen\Bundle\BlockManagerDebugBundle\DataCollector\BlockManagerDataCollector
        arguments:
            - "@netgen_block_manager.templating.global_variable"
            - "@twig"
        tags:
            - { name: data_collector, template: '@NetgenBlockManagerDebug/data_collector/ngbm.html.twig', id: ngbm }

    netgen_block_manager.event_listener.debug.data_collector.block_view:
        class: Netgen\Bundle\BlockManagerDebugBundle\EventListener\DataCollector\BlockViewListener
        arguments:
            - "@netgen_block_manager.debug.data_collector"
            - "%netgen_block_manager.debug.block_collector.enabled_contexts%"
        tags:
            - { name: kernel.event_subscriber }
