assets:
    packages:
        ngbm_css:
            base_path: '/bundles/netgenlayouts/css'
            version: '%ngbm.asset.version%'
            version_format: '%%s?%%s'
        ngbm_js:
            base_path: '/bundles/netgenlayouts/js'
            version: '%ngbm.asset.version%'
            version_format: '%%s?%%s'
        ngbm_dev_css:
            base_path: '/bundles/netgenlayouts/dev/css'
            version: '%ngbm.asset.version%'
            version_format: '%%s?%%s'
        ngbm_dev_js:
            base_path: '/bundles/netgenlayouts/dev/js'
            version: '%ngbm.asset.version%'
            version_format: '%%s?%%s'
        ngbm:
            base_path: '/bundles/netgenlayouts'
            version: '%ngbm.asset.version%'
            version_format: '%%s?%%s'
