parameters:
    netgen_layouts.route_prefix: /bm
    netgen_block_manager.route_prefix: '%netgen_layouts.route_prefix%'
    netgen_block_manager.block_view.collection_results_contexts: ['default', 'api']
    netgen_block_manager.block_view.collection_pager_contexts: ['ajax']
    netgen_block_manager.api.csrf_token_id: ngbm_api
    netgen_block_manager.collection.max_limit: 200
    netgen_block_manager.collection.contextual_limit: 12
    netgen_block_manager.collection.pager.template: '@@NetgenLayouts/collection/default_pager.html.twig'
