_nglayouts_admin:
    resource: "@NetgenLayoutsAdminBundle/Resources/config/routing/admin.yml"

_nglayouts_app:
    resource: "@NetgenLayoutsAdminBundle/Resources/config/routing/app.yml"

_nglayouts_api:
    resource: "@NetgenLayoutsAdminBundle/Resources/config/routing/api.yml"
    prefix: /app/api

nglayouts_ajax_block:
    path: /ajax/block/{blockId}/{locale}/{collectionIdentifier}
    methods: [GET]
    defaults:
        _controller: 'netgen_layouts.controller.block.view_ajax_block'
        _nglayouts_status: published

nglayouts_root:
    path: /
