_nglayouts_admin:
    resource: "@NetgenLayoutsAdminBundle/Resources/config/routing/admin.yaml"

_nglayouts_app:
    resource: "@NetgenLayoutsAdminBundle/Resources/config/routing/app.yaml"

_nglayouts_app_api:
    resource: "@NetgenLayoutsAdminBundle/Resources/config/routing/api.yaml"
    prefix: /app/api

nglayouts_ajax_block:
    path: /ajax/block/{blockId}/{locale}/{collectionIdentifier}
    controller: netgen_layouts.controller.block.view_ajax_block
    methods: [GET]
    defaults:
        _nglayouts_status: published

nglayouts_ajax_block_draft:
    path: /ajax/block/{blockId}/{locale}/{collectionIdentifier}/draft
    controller: netgen_layouts.controller.block.view_ajax_block
    methods: [GET]
    defaults:
        _nglayouts_status: draft

nglayouts_root:
    path: /
