_nglayouts_api_v1:
    resource: "routing/api_v1.yml"
    prefix: /api/v1

_nglayouts_admin:
    resource: "@NetgenLayoutsAdminBundle/Resources/config/routing/admin.yml"

_nglayouts_app:
    resource: "@NetgenLayoutsAdminBundle/Resources/config/routing/app.yml"

nglayouts_ajax_block:
    path: /ajax/block/{blockId}/{locale}/{collectionIdentifier}
    methods: [GET]
    defaults:
        _controller: 'nglayouts_ajax_block'
        _nglayouts_status: published

nglayouts_root:
    path: /
