view:
    rule_condition_view:
        value:
            route_parameter:
                template: "@NetgenLayoutsAdmin/admin/layout_resolver/condition/value/route_parameter.html.twig"
                match:
                    rule_condition\type: route_parameter
            query_parameter:
                template: "@NetgenLayoutsAdmin/admin/layout_resolver/condition/value/query_parameter.html.twig"
                match:
                    rule_condition\type: query_parameter
            exception:
                template: "@NetgenLayoutsAdmin/admin/layout_resolver/condition/value/exception.html.twig"
                match:
                    rule_condition\type: exception
            time:
                template: "@NetgenLayoutsAdmin/admin/layout_resolver/condition/value/time.html.twig"
                match:
                    rule_condition\type: time
        admin:
            rule_condition:
                template: "@NetgenLayoutsAdmin/admin/layout_resolver/condition/condition.html.twig"
                match:
                    rule_condition\is_group_condition: false
            rule_group_condition:
                template: "@NetgenLayoutsAdmin/admin/layout_resolver/condition/group_condition.html.twig"
                match:
                    rule_condition\is_group_condition: true
            rule_condition_invalid:
                template: "@NetgenLayoutsAdmin/admin/layout_resolver/condition/invalid_condition.html.twig"
                match:
                    rule_condition\type: "null"
                    rule_condition\is_group_condition: false
            rule_group_condition_invalid:
                template: "@NetgenLayoutsAdmin/admin/layout_resolver/condition/invalid_group_condition.html.twig"
                match:
                    rule_condition\type: "null"
                    rule_condition\is_group_condition: true
