view:
    rule_condition_view:
        value:
            route_parameter:
                template: "@NetgenLayoutsAdmin/admin/layout_resolver/condition/value/route_parameter.html.twig"
                match:
                    rule_condition\type: route_parameter
            query_parameter:
                template: "@NetgenLayoutsAdmin/admin/layout_resolver/condition/value/query_parameter.html.twig"
                match:
                    rule_condition\type: query_parameter
            exception:
                template: "@NetgenLayoutsAdmin/admin/layout_resolver/condition/value/exception.html.twig"
                match:
                    rule_condition\type: exception
            time:
                template: "@NetgenLayoutsAdmin/admin/layout_resolver/condition/value/time.html.twig"
                match:
                    rule_condition\type: time
        admin:
            invalid:
                template: "@NetgenLayoutsAdmin/admin/layout_resolver/condition/invalid_condition.html.twig"
                match:
                    rule_condition\type: "null"
