services:
    Netgen\Layouts\API\Service\LayoutService: "@netgen_layouts.api.service.layout"
    Netgen\Layouts\API\Service\BlockService: "@netgen_layouts.api.service.block"
    Netgen\Layouts\API\Service\CollectionService: "@netgen_layouts.api.service.collection"
    Netgen\Layouts\API\Service\LayoutResolverService: "@netgen_layouts.api.service.layout_resolver"
    Netgen\Layouts\API\Service\TransactionService: "@netgen_layouts.api.service.transaction"

    Netgen\Layouts\Block\Registry\BlockDefinitionRegistry: "@netgen_layouts.block.registry.block_definition"
    Netgen\Layouts\Block\Registry\BlockTypeRegistry: "@netgen_layouts.block.registry.block_type"
    Netgen\Layouts\Block\Registry\BlockTypeGroupRegistry: "@netgen_layouts.block.registry.block_type_group"
    Netgen\Layouts\Block\Registry\HandlerPluginRegistry: "@netgen_layouts.block.registry.handler_plugin"
    Netgen\Layouts\Collection\Registry\ItemDefinitionRegistry: "@netgen_layouts.collection.registry.item_definition"
    Netgen\Layouts\Collection\Registry\QueryTypeRegistry: "@netgen_layouts.collection.registry.query_type"
    Netgen\Layouts\Item\Registry\ValueTypeRegistry: "@netgen_layouts.item.registry.value_type"
    Netgen\Layouts\Layout\Registry\LayoutTypeRegistry: "@netgen_layouts.layout.registry.layout_type"
    Netgen\Layouts\Layout\Resolver\Registry\ConditionTypeRegistry: "@netgen_layouts.layout.resolver.registry.condition_type"
    Netgen\Layouts\Layout\Resolver\Registry\TargetTypeRegistry: "@netgen_layouts.layout.resolver.registry.target_type"
    Netgen\Layouts\Parameters\Registry\ParameterTypeRegistry: "@netgen_layouts.parameters.registry.parameter_type"

    Netgen\Layouts\View\ViewBuilderInterface: "@netgen_layouts.view.view_builder"
    Netgen\Layouts\View\ViewRendererInterface: "@netgen_layouts.view.view_renderer"
    Netgen\Layouts\Item\CmsItemBuilderInterface: "@netgen_layouts.item.item_builder"
    Netgen\Layouts\Item\CmsItemLoaderInterface: "@netgen_layouts.item.item_loader"
    Netgen\Layouts\Item\UrlGeneratorInterface: "@netgen_layouts.item.url_generator"
    Netgen\Layouts\Layout\Resolver\LayoutResolverInterface: "@netgen_layouts.layout.resolver"
    Netgen\Layouts\Collection\Result\ResultBuilderInterface: "@netgen_layouts.collection.result_builder"
    Netgen\Layouts\HttpCache\InvalidatorInterface: "@netgen_layouts.http_cache.invalidator"
    Netgen\Layouts\Transfer\Output\SerializerInterface: "@netgen_layouts.transfer.serializer"
    Netgen\Layouts\Transfer\Input\ImporterInterface: "@netgen_layouts.transfer.importer"
