parameters:
    netgen_layouts.block.block_definition.handler.plugin.common.groups: ['design', 'common']

    netgen_layouts.block.block_definition.handler.plugin.paged_collections.groups: ['design']
    netgen_layouts.block.block_definition.handler.plugin.paged_collections.pager_types:
        pager: 'Pager'
        load_more: 'Load more'

services:
    netgen_layouts.block.block_definition_factory:
        class: Netgen\Layouts\Block\BlockDefinitionFactory
        arguments:
            - "@netgen_layouts.parameters.translatable_parameter_builder_factory"
            - "@netgen_layouts.block.registry.handler_plugin"
            - "@netgen_layouts.config.config_definition_factory"

    netgen_layouts.block.registry.block_definition:
        class: Netgen\Layouts\Block\Registry\BlockDefinitionRegistry
        public: true
        arguments:
            - []

    netgen_layouts.block.registry.handler_plugin:
        class: Netgen\Layouts\Block\Registry\HandlerPluginRegistry
        arguments:
            - !tagged netgen_layouts.block_definition_handler.plugin

    netgen_layouts.block.registry.block_type:
        class: Netgen\Layouts\Block\Registry\BlockTypeRegistry
        public: true
        arguments:
            - []

    netgen_layouts.block.registry.block_type_group:
        class: Netgen\Layouts\Block\Registry\BlockTypeGroupRegistry
        public: true
        arguments:
            - []

    # Various block plugins

    netgen_layouts.block.block_definition.handler.plugin.common:
        class: Netgen\Layouts\Block\BlockDefinition\Handler\CommonParametersPlugin
        arguments:
            - "%netgen_layouts.block.block_definition.handler.plugin.common.groups%"
        tags:
            - { name: netgen_layouts.block_definition_handler.plugin, priority: 0 }

    netgen_layouts.block.block_definition.handler.plugin.paged_collections:
        class: Netgen\Layouts\Block\BlockDefinition\Handler\PagedCollectionsPlugin
        arguments:
            - "%netgen_layouts.block.block_definition.handler.plugin.paged_collections.pager_types%"
            - "%netgen_layouts.block.block_definition.handler.plugin.paged_collections.groups%"
        tags:
            - { name: netgen_layouts.block_definition_handler.plugin, priority: 10 }
