services:
    netgen_layouts.command.migration.query_offset_limit:
        class: Netgen\Bundle\LayoutsBundle\Command\Migration\MigrateQueryOffsetLimitCommand
        arguments:
            - "@netgen_layouts.collection.registry.query_type"
            - "@database_connection"
        tags:
            - { name: console.command, command: nglayouts:migration:query_offset_limit }

    netgen_layouts.command.migration.uuid:
        class: Netgen\Bundle\LayoutsBundle\Command\Migration\MigrateUuidCommand
        arguments:
            - "@database_connection"
        tags:
            - { name: console.command, command: nglayouts:migration:uuid }

    netgen_layouts.command.export:
        class: Netgen\Bundle\LayoutsBundle\Command\ExportCommand
        arguments:
            - "@netgen_layouts.transfer.serializer"
        tags:
            - { name: console.command, command: nglayouts:export }

    netgen_layouts.command.import:
        class: Netgen\Bundle\LayoutsBundle\Command\ImportCommand
        arguments:
            - "@netgen_layouts.transfer.importer"
        tags:
            - { name: console.command, command: nglayouts:import }
