services:
    netgen_block_manager.context:
        class: Netgen\Layouts\Context\Context

    netgen_block_manager.context.builder:
        class: Netgen\Layouts\Context\ContextBuilder
        arguments:
            - !tagged netgen_block_manager.context.provider
