services:
    netgen_layouts.controller.base:
        class: Netgen\Bundle\LayoutsBundle\Controller\AbstractController
        abstract: true
        calls:
            - [setContainer, ["@service_container"]]

    # Frontend controllers

    netgen_layouts.controller.block.view_ajax_block:
        class: Netgen\Bundle\LayoutsBundle\Controller\Block\ViewAjaxBlock
        public: true
        parent: netgen_layouts.controller.base
        arguments:
            - "@netgen_layouts.error.handler"
