services:
    netgen_layouts.design.twig.filesystem_loader:
        class: Netgen\Bundle\LayoutsBundle\Design\Twig\FilesystemLoader
        decorates: twig.loader.native_filesystem
        arguments:
            - "@netgen_layouts.design.twig.filesystem_loader.inner"
            - "@netgen_layouts.configuration"
        tags:
            - { name: twig.loader }
