services:
    netgen_block_manager.error.handler:
        alias: netgen_block_manager.error.handler.debug

    netgen_block_manager.error.handler.debug:
        class: Netgen\BlockManager\Error\DebugErrorHandler
        arguments:
            - "@?logger"
            - "%kernel.debug%"
        tags:
            - { name: monolog.logger, channel: ngbm }
