services:
    netgen_block_manager.http_cache.fos.cache_manager:
        synthetic: true

    netgen_block_manager.http_cache.client:
        alias: netgen_block_manager.http_cache.client.varnish

    netgen_block_manager.http_cache.client.varnish:
        class: Netgen\BlockManager\HttpCache\VarnishClient
        arguments:
            - "@netgen_block_manager.http_cache.fos.cache_manager"
            - "@netgen_block_manager.http_cache.layout.id_provider"

    netgen_block_manager.http_cache.client.null:
        class: Netgen\BlockManager\HttpCache\NullClient

    netgen_block_manager.http_cache.tagger:
        class: Netgen\BlockManager\HttpCache\Tagger

    netgen_block_manager.http_cache.layout.id_provider:
        class: Netgen\BlockManager\HttpCache\Layout\IdProvider
        arguments:
            - "@netgen_block_manager.api.service.layout"
