services:
    netgen_layouts.http_cache.fos.cache_manager:
        synthetic: true

    netgen_layouts.http_cache.client:
        alias: netgen_layouts.http_cache.client.varnish

    netgen_layouts.http_cache.client.varnish:
        class: Netgen\Layouts\HttpCache\VarnishClient
        arguments:
            - "@netgen_layouts.http_cache.fos.cache_manager"
            - "@netgen_layouts.http_cache.layout.id_provider"

    netgen_layouts.http_cache.client.null:
        class: Netgen\Layouts\HttpCache\NullClient

    netgen_layouts.http_cache.tagger:
        class: Netgen\Layouts\HttpCache\Tagger

    netgen_layouts.http_cache.layout.id_provider:
        class: Netgen\Layouts\HttpCache\Layout\IdProvider
        arguments:
            - "@netgen_layouts.api.service.layout"
