services:
    netgen_block_manager.normalizer.value:
        class: Netgen\Layouts\Serializer\Normalizer\ValueNormalizer
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.exception:
        class: Netgen\Layouts\Serializer\Normalizer\ExceptionNormalizer
        arguments:
            - "%kernel.debug%"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.view:
        class: Netgen\Layouts\Serializer\Normalizer\V1\ViewNormalizer
        arguments:
            - "@netgen_block_manager.view.renderer"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.parameter:
        class: Netgen\Layouts\Serializer\Normalizer\V1\ParameterNormalizer
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.block:
        class: Netgen\Layouts\Serializer\Normalizer\V1\BlockNormalizer
        arguments:
            - "@netgen_block_manager.api.service.block"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.placeholder:
        class: Netgen\Layouts\Serializer\Normalizer\V1\PlaceholderNormalizer
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.layout:
        class: Netgen\Layouts\Serializer\Normalizer\V1\LayoutNormalizer
        arguments:
            - "@netgen_block_manager.api.service.layout"
            - "@netgen_block_manager.api.service.block"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.collection:
        class: Netgen\Layouts\Serializer\Normalizer\V1\CollectionNormalizer
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.collection_item:
        class: Netgen\Layouts\Serializer\Normalizer\V1\CollectionItemNormalizer
        arguments:
            - "@netgen_block_manager.item.url_generator"
            - "@netgen_block_manager.collection.item_visibility_resolver"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.collection_query:
        class: Netgen\Layouts\Serializer\Normalizer\V1\CollectionQueryNormalizer
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.collection_result_set:
        class: Netgen\Layouts\Serializer\Normalizer\V1\CollectionResultSetNormalizer
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.collection_result:
        class: Netgen\Layouts\Serializer\Normalizer\V1\CollectionResultNormalizer
        arguments:
            - "@netgen_block_manager.item.url_generator"
            - "@netgen_block_manager.collection.item_visibility_resolver"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.block_type:
        class: Netgen\Layouts\Serializer\Normalizer\V1\BlockTypeNormalizer
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.block_type_group:
        class: Netgen\Layouts\Serializer\Normalizer\V1\BlockTypeGroupNormalizer
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.layout_type:
        class: Netgen\Layouts\Serializer\Normalizer\V1\LayoutTypeNormalizer
        tags:
            - { name: serializer.normalizer }
