services:
    netgen_layouts.param_converter.block.block:
        class: Netgen\Bundle\LayoutsBundle\ParamConverter\Block\BlockParamConverter
        arguments:
            - "@netgen_layouts.api.service.block"
        tags:
            - { name: request.param_converter, priority: 0 }

    netgen_layouts.param_converter.layout.zone:
        class: Netgen\Bundle\LayoutsBundle\ParamConverter\Layout\ZoneParamConverter
        arguments:
            - "@netgen_layouts.api.service.layout"
        tags:
            - { name: request.param_converter, priority: 0 }

    netgen_layouts.param_converter.layout.layout:
        class: Netgen\Bundle\LayoutsBundle\ParamConverter\Layout\LayoutParamConverter
        arguments:
            - "@netgen_layouts.api.service.layout"
        tags:
            - { name: request.param_converter, priority: 0 }

    netgen_layouts.param_converter.collection.collection:
        class: Netgen\Bundle\LayoutsBundle\ParamConverter\Collection\CollectionParamConverter
        arguments:
            - "@netgen_layouts.api.service.collection"
        tags:
            - { name: request.param_converter, priority: 0 }

    netgen_layouts.param_converter.collection.item:
        class: Netgen\Bundle\LayoutsBundle\ParamConverter\Collection\ItemParamConverter
        arguments:
            - "@netgen_layouts.api.service.collection"
        tags:
            - { name: request.param_converter, priority: 0 }

    netgen_layouts.param_converter.collection.query:
        class: Netgen\Bundle\LayoutsBundle\ParamConverter\Collection\QueryParamConverter
        arguments:
            - "@netgen_layouts.api.service.collection"
        tags:
            - { name: request.param_converter, priority: 0 }

    netgen_layouts.param_converter.layout_resolver.rule:
        class: Netgen\Bundle\LayoutsBundle\ParamConverter\LayoutResolver\RuleParamConverter
        arguments:
            - "@netgen_layouts.api.service.layout_resolver"
        tags:
            - { name: request.param_converter, priority: 0 }

    netgen_layouts.param_converter.layout_resolver.condition:
        class: Netgen\Bundle\LayoutsBundle\ParamConverter\LayoutResolver\ConditionParamConverter
        arguments:
            - "@netgen_layouts.api.service.layout_resolver"
        tags:
            - { name: request.param_converter, priority: 0 }

    netgen_layouts.param_converter.layout_resolver.target:
        class: Netgen\Bundle\LayoutsBundle\ParamConverter\LayoutResolver\TargetParamConverter
        arguments:
            - "@netgen_layouts.api.service.layout_resolver"
        tags:
            - { name: request.param_converter, priority: 0 }
