services:
    netgen_block_manager.templating.plugin_renderer:
        class: Netgen\Bundle\LayoutsBundle\Templating\Plugin\Renderer
        arguments:
            - "@twig"
            - []

    netgen_block_manager.templating.global_variable:
        class: Netgen\Bundle\LayoutsBundle\Templating\Twig\GlobalVariable
        arguments:
            - "@netgen_block_manager.configuration"
            - "@netgen_block_manager.layout.resolver"
            - "@netgen_block_manager.templating.pagelayout_resolver"
            - "@netgen_block_manager.view.view_builder"
            - "@request_stack"
            - "%netgen_layouts.debug%"

    netgen_block_manager.templating.twig.extension.rendering:
        class: Netgen\Bundle\LayoutsBundle\Templating\Twig\Extension\RenderingExtension
        tags:
            - { name: twig.extension }

    netgen_block_manager.templating.twig.runtime.rendering:
        class: Netgen\Bundle\LayoutsBundle\Templating\Twig\Runtime\RenderingRuntime
        arguments:
            - "@netgen_block_manager.api.service.block"
            - "@netgen_block_manager.view.renderer"
            - "@netgen_block_manager.locale.provider"
            - "@request_stack"
            - "@netgen_block_manager.error.handler"
        tags:
            - { name: twig.runtime }

    netgen_block_manager.templating.twig.extension.plugin_rendering:
        class: Netgen\Bundle\LayoutsBundle\Templating\Twig\Extension\PluginRenderingExtension
        tags:
            - { name: twig.extension }

    netgen_block_manager.templating.twig.runtime.plugin_rendering:
        class: Netgen\Bundle\LayoutsBundle\Templating\Twig\Runtime\PluginRenderingRuntime
        arguments:
            - "@netgen_block_manager.templating.plugin_renderer"
            - "@netgen_block_manager.error.handler"
        tags:
            - { name: twig.runtime }

    netgen_block_manager.templating.twig.extension.collection_pager:
        class: Netgen\Bundle\LayoutsBundle\Templating\Twig\Extension\CollectionPagerExtension
        tags:
            - { name: twig.extension }

    netgen_block_manager.templating.twig.runtime.collection_pager:
        class: Netgen\Bundle\LayoutsBundle\Templating\Twig\Runtime\CollectionPagerRuntime
        arguments:
            - "@netgen_block_manager.templating.twig.runtime.collection_pager.route_generator"
            - "@netgen_block_manager.collection.result.pagerfanta.view"
        tags:
            - { name: twig.runtime }

    netgen_block_manager.templating.twig.runtime.collection_pager.route_generator:
        class: Netgen\Bundle\LayoutsBundle\Templating\Twig\Runtime\CollectionPager\RouteGenerator
        arguments:
            - "@netgen_block_manager.context"
            - "@uri_signer"
            - "@router"

    netgen_block_manager.templating.twig.extension.item:
        class: Netgen\Bundle\LayoutsBundle\Templating\Twig\Extension\ItemExtension
        tags:
            - { name: twig.extension }

    netgen_block_manager.templating.twig.runtime.item:
        class: Netgen\Bundle\LayoutsBundle\Templating\Twig\Runtime\ItemRuntime
        arguments:
            - "@netgen_block_manager.item.item_loader"
            - "@netgen_block_manager.item.url_generator"
            - "@netgen_block_manager.error.handler"
        tags:
            - { name: twig.runtime }

    netgen_block_manager.templating.twig.extension.helpers:
        class: Netgen\Bundle\LayoutsBundle\Templating\Twig\Extension\HelpersExtension
        tags:
            - { name: twig.extension }

    netgen_block_manager.templating.twig.runtime.helpers:
        class: Netgen\Bundle\LayoutsBundle\Templating\Twig\Runtime\HelpersRuntime
        arguments:
            - "@netgen_block_manager.api.service.layout"
        tags:
            - { name: twig.runtime }

    netgen_block_manager.templating.pagelayout_resolver.default:
        class: Netgen\Bundle\LayoutsBundle\Templating\PageLayoutResolver
        arguments:
            - "%netgen_layouts.pagelayout%"

    netgen_block_manager.templating.pagelayout_resolver:
        alias: netgen_block_manager.templating.pagelayout_resolver.default
