services:
    netgen_layouts.transfer.serializer:
        class: Netgen\Layouts\Transfer\Output\Serializer
        arguments:
            - "@netgen_layouts.api.service.layout"
            - "@netgen_layouts.api.service.layout_resolver"
            - "@netgen_layouts.transfer.serializer.visitor.aggregate"

    netgen_layouts.transfer.input.data_handler.layout:
        class: Netgen\Layouts\Transfer\Input\DataHandler\LayoutDataHandler
        arguments:
            - "@netgen_layouts.api.service.block"
            - "@netgen_layouts.api.service.collection"
            - "@netgen_layouts.api.service.layout"
            - "@netgen_layouts.block.registry.block_definition"
            - "@netgen_layouts.layout.registry.layout_type"
            - "@netgen_layouts.collection.registry.item_definition"
            - "@netgen_layouts.collection.registry.query_type"
            - "@netgen_layouts.item.item_loader"

    netgen_layouts.transfer.input.json_validator:
        class: Netgen\Layouts\Transfer\Input\JsonValidator

    netgen_layouts.transfer.input.importer:
        class: Netgen\Layouts\Transfer\Input\Importer
        arguments:
            - "@netgen_layouts.transfer.input.json_validator"
            - "@netgen_layouts.transfer.input.data_handler.layout"
