name: Behat

on:
  push:
    branches:
      - 'master'
      - 'ghactions'
      - '[0-9].[0-9]+'
  pull_request: ~

jobs:
  behat:
    name: Behat
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none

      # Install Flex as a global dependency to enable usage of extra.symfony.require
      # while keeping Flex recipes from applying
      - run: composer global require --no-scripts symfony/flex

      - run: composer config extra.symfony.require ~5.2.0

      - run: composer update --prefer-dist

      - run: ./tests/prepare_behat.sh > /dev/null 2>&1 &

      # Sleep to allow the script to download Chrome WebDriver
      - run: sleep 15

      - run: composer behat-headless
